# -------- Config --------
PYTHON_VERSION := $(shell cat .python-version 2>/dev/null || echo "3.14.3")

REQ := requirements.txt
REQ_DEV := requirements-dev.txt
REQ_FREEZE := requirements.freeze.txt

# -------- Phony Targets --------
.PHONY: install install-dev update clean freeze check list help

# -------- Targets --------
install: ## Install production dependencies
	@if [ -f $(REQ) ]; then \
		uv pip install -r $(REQ); \
	else \
		echo "No $(REQ) found"; \
	fi

install-dev: ## Install development dependencies
	@if [ -f $(REQ_DEV) ]; then \
		uv pip install -r $(REQ_DEV); \
	else \
		echo "No $(REQ_DEV) found"; \
	fi

update: ## Upgrade dependencies
	@if [ -f $(REQ) ]; then \
		uv pip install --upgrade -r $(REQ); \
	fi

clean: ## Remove build/cache artifacts
	@echo "Cleaning Python artifacts..."
	@find . -type d -name "__pycache__" -prune -exec rm -rf {} + 2>/dev/null || true
	@find . -type f -name "*.pyc" -delete
	@rm -rf .pytest_cache .mypy_cache .coverage htmlcov
	@rm -rf dist build *.egg-info

freeze: ## Freeze current environment
	@echo "# Auto-generated by \`make freeze\` — do not edit manually" > $(REQ_FREEZE)
	uv pip freeze >> $(REQ_FREEZE)

check: ## Check dependency issues
	uv pip check

list: ## List installed packages
	uv pip list

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*## ' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'
